language: php
os: linux

services:
  - docker

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

env:
  # Laravel 5.7 Jobs
  - MYSQL_VERSION=5.7 PG_VERSION=9.1 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  - MYSQL_VERSION=8.0 PG_VERSION=9.2 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  - MARIA_VERSION=5.5 PG_VERSION=9.3 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  - MARIA_VERSION=10.0 PG_VERSION=9.4 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  - MARIA_VERSION=10.1 PG_VERSION=9.5 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  - MARIA_VERSION=10.2 PG_VERSION=9.6 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  - MARIA_VERSION=10.3 PG_VERSION=10 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  - MARIA_VERSION=10.4 PG_VERSION=11 LA_VERSION="5.7.*" PU_VERSION="^7.0"
  # Laravel 5.8 Jobs
  - MYSQL_VERSION=5.7 PG_VERSION=9.1 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  - MYSQL_VERSION=8.0 PG_VERSION=9.2 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  - MARIA_VERSION=5.5 PG_VERSION=9.3 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  - MARIA_VERSION=10.0 PG_VERSION=9.4 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  - MARIA_VERSION=10.1 PG_VERSION=9.5 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  - MARIA_VERSION=10.2 PG_VERSION=9.6 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  - MARIA_VERSION=10.3 PG_VERSION=10 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  - MARIA_VERSION=10.4 PG_VERSION=11 LA_VERSION="5.8.*" PU_VERSION="^8.0"
  # Laravel 6.* Jobs
  - MYSQL_VERSION=5.7 PG_VERSION=9.1 LA_VERSION="^6.0" PU_VERSION="^8.0"
  - MYSQL_VERSION=8.0 PG_VERSION=9.2 LA_VERSION="^6.0" PU_VERSION="^8.0"
  - MARIA_VERSION=5.5 PG_VERSION=9.3 LA_VERSION="^6.0" PU_VERSION="^8.0"
  - MARIA_VERSION=10.0 PG_VERSION=9.4 LA_VERSION="^6.0" PU_VERSION="^8.0"
  - MARIA_VERSION=10.1 PG_VERSION=9.5 LA_VERSION="^6.0" PU_VERSION="^8.0"
  - MARIA_VERSION=10.2 PG_VERSION=9.6 LA_VERSION="^6.0" PU_VERSION="^8.0"
  - MARIA_VERSION=10.3 PG_VERSION=10 LA_VERSION="^6.0" PU_VERSION="^8.0"
  - MARIA_VERSION=10.4 PG_VERSION=11 LA_VERSION="^6.0" PU_VERSION="^8.0"

jobs:
  allow_failures:
    - php: nightly

before_install:
  - sudo /etc/init.d/mysql stop
  - |
    if [ -n "${MYSQL_VERSION}" ]
    then
      make -C tests/ start_db_mysql oV=${MYSQL_VERSION}
    else
      make -C tests/ start_db_maria mV=${MARIA_VERSION}
    fi
  - sudo /etc/init.d/postgresql stop
  - make -C tests/ start_db_postgres pV=${PG_VERSION}

install:
  - composer require --dev --no-suggest --no-update laravel/laravel:${LA_VERSION} phpunit/phpunit:${PU_VERSION}
  - travis_retry composer install --no-suggest

before_script:
  - mkdir -p build/logs
  - "echo -n 'Ensuring MySQL/MariaDB is ready: '; ./tests/wait_container spatial-mysql ; echo done"
  - "echo -n 'Ensuring PostgreSQL DB is ready: '; ./tests/wait_container spatial-postgres ; echo done"

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --prepend .coverage-filter.php

after_script:
  - |
    if [ -n "${MYSQL_VERSION}" ]
    then
      make -C tests/ rm_db_mysql oV=${MYSQL_VERSION}
    else
      make -C tests/ rm_db_maria mV=${MARIA_VERSION}
    fi
  - make -C tests/ rm_db_postgres pV=${PG_VERSION}

after_success:
  - bash <(curl -s https://codecov.io/bash)
